server:
  port: 1601

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsdb_dev
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
news-api:
  news-api-key: 992fc964aa274fe4bc82ae89593e4be3
  news-api-url: https://newsapi.org/v2/top-headlines

services:
  location-service:
    get-locations-names-and-ids-list: http://localhost:1602/locations/names