server:
  port: 1603

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aggregationdb_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

services:
  location-service:
    get-locations-list: http://localhost:1602/locations
    location-details-by-id: http://localhost:1602/locations/id/
  news-service:
    news-by-location-id: http://localhost:1601/news/location/

