server:
  port: 1603

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aggregationdb_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

services:
  location-service:
    locations-url: http://localhost:1602/locations
    location-details-by-id: http://localhost:1602/locations/id/
  news-service:
    news-by-location-id: http://localhost:1601/news/location/

open-weather-api:
  api-key: 8dd10aa84818189acdb5e9f1a63986a5
  api-url-location-details-by-location-name: https://api.openweathermap.org/geo/1.0/direct?q=%s&limit=1&appid=%s
  api-url-location-details-by-coordinates: "https://api.openweathermap.org/geo/1.0/reverse?lat=%f&lon=%f&limit=1&appid=%s

