server:
  port: 1602

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/locationdb_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
